# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome OurPerfectWorld, Enjoy It!
email: 276293337@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Learning By Doing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: NULL
github_username:  OurPerfectWorld

# Build settings
# markdown: kramdown
markdown: redcarpet     #设置md的渲染引擎
highlighter: rouge
auto: true